name: CI - latex-action
on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
      - uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: caleb-jasik-resume.tex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
